version: "2"
services:
  db:
#    image: mysql
    image: mysql:5.7
    container_name: db
#    restart:  always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: project_db
      MYSQL_USER: user_1
      MYSQL_PASSWORD: 11111111
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - front-end

  web:
    build: ./docker/web
    container_name: web
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - front-end
    depends_on:
      - db


networks:
  front-end: